### ISSUE TITLE
8443 port for director is not mentioned for 2.0,2.1 and 2.2 documentation

### ISSUE THREAD

**Issue by arunavasan** [pivotal-cf/docs-pcf-security#14]
https://github.com/pivotal-cf/docs-pcf-security/blob/6aa2f4b3a0083fc6f8e28a296ceb9f0f562ae5ff/networking/loggregator-network-paths.html.md.erb#L78

only 25595 is mentioned but user gets this error we are getting the following error in the bosh-system-metrics-forwarder logs on the loggregator nodes:
```unable to get token: Post https://<director>:8443/oauth/token: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)```

**Comment by pspinrad** [comment]
Thanks, @arunavasan  - docs now list both port numbers:
https://docs.pivotal.io/pivotalcf/2-2/security/networking/loggregator-network-paths.html
