### ISSUE TITLE
Please be specific for network port and protocol that diego cell uses to PAS blobstore

### ISSUE THREAD

**Issue by doddatpivotal** [pivotal-cf/docs-pcf-security#43]
https://docs.pivotal.io/pivotalcf/2-4/security/networking/diego-network-paths.html#outbound lists diego outbound connections.

There is a row for diego cell (rep) communicating to the nfs_server/blobstore.  It indicates "Varies" due to the optional target for blob store.  The footnote explains that it is option, but does not provide the port number in the event that they use the PAS internal blob store. The docs would be better if we indicated what port is required for internal PAS blob store.  

Via internal slack with capi cf-capi team, it was determined to be TLS over 4443.  https://pivotal.slack.com/archives/C3LV25ZCM/p1551192077049900 .  Please consider updating the documentation footnote with this information.

**Comment by ljarzynski** [comment]
Thanks @doddatpivotal for suggesting this improvement. I've pushed this fix to all branches: https://github.com/pivotal-cf/docs-pcf-security/commit/e1f99031536e897f70774327b3c4202ad758194b. The update should be reflected on the production site shortly.
