### ISSUE TITLE
Missing Quote in Curl Command?

### ISSUE THREAD

**Issue by bbtong** [pivotal-cf/docs-pcf-security#54]
**The docs currently show:**

> Retrieve the Ops Manager Root CA as a File
To return the Ops Manager root CA as a file, use curl to make the following API call:

```
curl "https://OPS-MAN-FQDN/download_root_ca_cert \
      -X GET \
      -H "Authorization: Bearer YOUR-UAA-ACCESS-TOKEN"
Where YOUR-UAA-ACCESS-TOKEN is your Ops Manager access token without any newline characters such as \n.
```

**I believe the command should be:**
```
curl "https://OPS-MAN-FQDN/download_root_ca_cert" \
      -X GET \
      -H "Authorization: Bearer YOUR-UAA-ACCESS-TOKEN"
Where YOUR-UAA-ACCESS-TOKEN is your Ops Manager access token without any newline characters such as \n.
```

Adding the `"` after `download_root_ca_cert` made the curl command work for me; else, I got this error following the docs:
```
curl: (6) Could not resolve host: Bearer
curl: (6) Could not resolve host: <redacted>
```

**Comment by mlimonczenko** [comment]
Thank you, @bbtong. I'm not sure I fully understand the request. The two example commands look the same to me.

Also, tell me which file you are referencing.

**Comment by bbtong** [comment]
https://docs.pivotal.io/pivotalcf/2-4/security/pcf-infrastructure/managing-certificates.html

The command here has mismatched quotes.  My `curl` commands have a difference of one `"`, added after download_root_ca_cert.

**Comment by animatedmax** [comment]
Hi @bbtong As you've no doubt seen, we added corrected the command as you described. Thank you very much for letting us know about it.
